- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "~/.config/git"
    - "{{ ansible_env.get('XDG_CONFIG_HOME', ansible_user_dir + '/.config') }}/readline"
    - "{{ ansible_env.get('XDG_STATE_HOME', ansible_user_dir + '/.local/state') }}"
    - "{{ ansible_env.get('XDG_CONFIG_HOME', ansible_user_dir + '/.config') }}/pg"
    - "{{ ansible_env.get('XDG_STATE_HOME', ansible_user_dir + '/.local/state') }}/zsh"
    - "~/files/Downloads"
    - "~/files/Documents"
    - "~/files/Photos"
    - "~/files/Screenshots"
    - "~/code/vscodeworkspaces"
