- name: Dev setup
  hosts: localhost
  tasks:
  - name: Brew
    include_tasks: ./brew.yaml
  - name: OS X Defaults
    include_tasks: ./defaults.yaml
  - name: Create Required Directories
    include_tasks: ./directories.yaml
  - name: Set Config Links
    include_tasks: ./config_links.yaml