- name: Dev setup
  hosts: localhost
  tasks:
    - name: Brew
      ansible.builtin.include_tasks:
        file: ./brew.yaml
        apply:
          tags: install, brew
      tags: install, brew
    - name: Pip
      ansible.builtin.include_tasks:
        file: ./pip.yaml
        apply:
          tags: install, pip
      tags: install, pip
    - name: OS X Defaults
      ansible.builtin.include_tasks:
        file: ./defaults.yaml
        apply:
          tags: install, defaults
      tags: dotfiles, defaults
    - name: Create Required Directories
      ansible.builtin.include_tasks:
        file: ./directories.yaml
        apply:
          tags: install, directories
      tags: dotfiles, directories
    - name: Set Config Links
      ansible.builtin.include_tasks:
        file: ./config_links.yaml
        apply:
          tags: install, config_links
      tags: dotfiles, config_links
