- name: Dev setup
  hosts: localhost
  tasks:
  - name: Install brew packages
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - gh
      - starship
  - name: Install base cask packages
    community.general.homebrew_cask:
      name: "{{ item }}"
      state: present
      accept_external_apps: true
    with_items:
      - android-file-transfer
      - audacity
      - caffeine
      - google-chrome
      - discord
      - hammerspoon
      - firefox
      - signal
      - spotify
      - visual-studio-code
      - vlc